# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shubu_client.ui'
#
# Created: Mon Mar  7 14:14:10 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 392)
        Form.setMinimumSize(QtCore.QSize(679, 392))
        self.time = QtGui.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(570, -10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Gurmukhi")
        font.setPointSize(47)
        font.setWeight(75)
        font.setBold(True)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.radioButton = QtGui.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(20, 60, 61, 18))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtGui.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 90, 71, 18))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtGui.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 120, 101, 18))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtGui.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 150, 51, 18))
        self.radioButton_4.setObjectName("radioButton_4")
        self.textEdit = QtGui.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(120, 20, 421, 211))
        self.textEdit.setObjectName("textEdit")
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(60, 350, 51, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 330, 56, 21))
        self.label_2.setObjectName("label_2")
        self.verticalScrollBar = QtGui.QScrollBar(Form)
        self.verticalScrollBar.setGeometry(QtCore.QRect(530, 20, 16, 211))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.textEdit_2 = QtGui.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 240, 291, 78))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 320, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.sendChat_button = QtGui.QPushButton(Form)
        self.sendChat_button.setGeometry(QtCore.QRect(320, 320, 91, 21))
        self.sendChat_button.setObjectName("sendChat_button")
        self.listView = QtGui.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(550, 50, 121, 181))
        self.listView.setObjectName("listView")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(430, 240, 231, 91))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_3 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_3.setGeometry(QtCore.QRect(-7, 17, 241, 81))
        self.textEdit_3.setObjectName("textEdit_3")
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 350, 391, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.browse_button = QtGui.QPushButton(Form)
        self.browse_button.setGeometry(QtCore.QRect(510, 350, 61, 21))
        self.browse_button.setObjectName("browse_button")
        self.submit_button = QtGui.QPushButton(Form)
        self.submit_button.setGeometry(QtCore.QRect(580, 350, 91, 21))
        self.submit_button.setObjectName("submit_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.time.setText(QtGui.QApplication.translate("Form", "7 : 55", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Form", "Java", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Form", "Python", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Form", "C language", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("Form", "C++", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "ShubU", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Question", None, QtGui.QApplication.UnicodeUTF8))
        self.sendChat_button.setText(QtGui.QApplication.translate("Form", "send", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Additional", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_button.setText(QtGui.QApplication.translate("Form", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_button.setText(QtGui.QApplication.translate("Form", "submit", None, QtGui.QApplication.UnicodeUTF8))

