# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Patipon\PycharmProjects\SoftEngProject\serverGUI.ui'
#
# Created: Thu Jan 28 10:53:44 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BroadCastList = QtGui.QListView(self.centralwidget)
        self.BroadCastList.setGeometry(QtCore.QRect(610, 400, 181, 161))
        self.BroadCastList.setObjectName("BroadCastList")
        self.BroadcastLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.BroadcastLineEdit.setGeometry(QtCore.QRect(610, 360, 141, 31))
        self.BroadcastLineEdit.setObjectName("BroadcastLineEdit")
        self.BroadcastButton = QtGui.QPushButton(self.centralwidget)
        self.BroadcastButton.setGeometry(QtCore.QRect(750, 360, 41, 31))
        self.BroadcastButton.setObjectName("BroadcastButton")
        self.ScoreBoard = QtGui.QTableView(self.centralwidget)
        self.ScoreBoard.setGeometry(QtCore.QRect(170, 130, 621, 221))
        self.ScoreBoard.setObjectName("ScoreBoard")
        self.AddButton = QtGui.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(10, 200, 71, 51))
        self.AddButton.setObjectName("AddButton")
        self.RemoveButton = QtGui.QPushButton(self.centralwidget)
        self.RemoveButton.setGeometry(QtCore.QRect(90, 200, 71, 51))
        self.RemoveButton.setObjectName("RemoveButton")
        self.TimeRemaining = QtGui.QLabel(self.centralwidget)
        self.TimeRemaining.setGeometry(QtCore.QRect(170, 50, 521, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(36)
        font.setWeight(50)
        font.setBold(False)
        self.TimeRemaining.setFont(font)
        self.TimeRemaining.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeRemaining.setObjectName("TimeRemaining")
        self.StartStopButton = QtGui.QPushButton(self.centralwidget)
        self.StartStopButton.setGeometry(QtCore.QRect(700, 40, 91, 81))
        self.StartStopButton.setObjectName("StartStopButton")
        self.HostName = QtGui.QLabel(self.centralwidget)
        self.HostName.setGeometry(QtCore.QRect(20, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HostName.setFont(font)
        self.HostName.setObjectName("HostName")
        self.IpAddrLabel = QtGui.QLabel(self.centralwidget)
        self.IpAddrLabel.setGeometry(QtCore.QRect(20, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IpAddrLabel.setFont(font)
        self.IpAddrLabel.setObjectName("IpAddrLabel")
        self.PortLabel = QtGui.QLabel(self.centralwidget)
        self.PortLabel.setGeometry(QtCore.QRect(20, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PortLabel.setFont(font)
        self.PortLabel.setObjectName("PortLabel")
        self.OnlineList = QtGui.QListWidget(self.centralwidget)
        self.OnlineList.setGeometry(QtCore.QRect(10, 260, 151, 301))
        self.OnlineList.setObjectName("OnlineList")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 360, 431, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.chatLogLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.chatLogLayout.setContentsMargins(0, 0, 0, 0)
        self.chatLogLayout.setObjectName("chatLogLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        hLayout = QtGui.QHBoxLayout()
        self.lineEdit = QtGui.QLineEdit()
        self.sendButton = QtGui.QPushButton("Send")
        self.tabWidget = QtGui.QTabWidget()
        hLayout.addWidget(self.lineEdit)
        hLayout.addWidget(self.sendButton)
        self.chatLogLayout.addWidget(self.tabWidget)
        self.chatLogLayout.addLayout(hLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.BroadcastButton.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.AddButton.setText(QtGui.QApplication.translate("MainWindow", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.TimeRemaining.setText(QtGui.QApplication.translate("MainWindow", "7 : 55", None, QtGui.QApplication.UnicodeUTF8))
        self.StartStopButton.setText(QtGui.QApplication.translate("MainWindow", "Start/Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.HostName.setText(QtGui.QApplication.translate("MainWindow", "ShubU", None, QtGui.QApplication.UnicodeUTF8))
        self.IpAddrLabel.setText(QtGui.QApplication.translate("MainWindow", "IP address 127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.PortLabel.setText(QtGui.QApplication.translate("MainWindow", "Port 3616", None, QtGui.QApplication.UnicodeUTF8))

